# KERNEL | TASKS | MAIN

- name: "HELPER VALIDATE CATALOG | maintenance"
  ansible.builtin.include_role:
    name: helpers
    tasks_from: h_catalog_validate.yml
  when: key_catalog.validate | bool

- name: "STAGE FACT | maintenance"
  ansible.builtin.include_role:
    name: helpers
    tasks_from: h_stage.yml
  vars: { stage_role: "kernel", stage_value: "{{ key_components.kernel.stage }}" }

- name: "GRUB | maintenance"
  ansible.builtin.include_role:
    name: helpers
    tasks_from: h_component_setup.yml
  vars: { component_group: "kernel", component_name: "grub" }
  when: key_components.kernel.grub.enabled | bool

- name: "SYSCTL | maintenance"
  ansible.builtin.include_role:
    name: helpers
    tasks_from: h_component_setup.yml
  vars: { component_group: "kernel", component_name: "sysctl" }
  when: key_components.kernel.sysctl.enabled | bool