all:
  children:
    ansible_controllers:
      hosts:
        ac_pc56:

    ingress_gateways:
      hosts:
        igw_lv_riga_s1:
        igw_ru_msc_s2:

    prod:
      children:
        ansible_controllers: {}
        ingress_gateways: {}